// Isolated repository regression checks: never access the user's browser or cloud.
const fs = require('node:fs')
const path = require('node:path')
const vm = require('node:vm')
const assert = require('node:assert/strict')
const memory = new Map()
const localStorage = { getItem: key => memory.get(key) ?? null, setItem: (key, value) => memory.set(key, value) }
async function load(relative, mocks = {}, globals = {}) {
  const { transformSync } = await import('rolldown/utils')
  const source = fs.readFileSync(path.join(__dirname, '..', relative), 'utf8')
  let output = transformSync(relative, source, { lang: 'ts' }).code
  output = output.replace(/import \{([^}]+)\} from ["']([^"']+)["'];?/g, (_, names, name) => 'const {' + names.replace(/ as /g, ': ') + '} = require(' + JSON.stringify(name) + ');')
  const exports = [...output.matchAll(/export (?:async )?(?:class|const|function) (\w+)/g)].map(match => match[1])
  output = output.replace(/export ((?:async )?(?:class|const|function)) /g, '$1 ') + '\nmodule.exports = {' + exports.join(',') + '}'
  const module = { exports: {} }
  vm.runInNewContext(output, { module, exports: module.exports, require: name => { if (name in mocks) return mocks[name]; throw new Error('Unexpected dependency: ' + name) }, localStorage, crypto: require('node:crypto').webcrypto, Date, JSON, ...globals })
  return module.exports
}
async function main() {
  const itemColors = await load('src/data/itemColors.ts')
  assert.throws(() => itemColors.checkedColor('red'))
  assert.equal(itemColors.checkedColor('#AABBCC'), '#aabbcc')
  const { projectEntryOccursOn, projectCalendar, projectWeekBars, visibleProjectEntries } = await load('src/data/projectCalendar.ts', { './itemColors': itemColors })
  const calendarTodo = { id: 't', projectId: 'one', kind: 'todo', date: '2026-10-10', endDate: null, completed: true, title: 'Todo', createdAt: 'now' }
  const calendarSchedule = { ...calendarTodo, id: 's', projectId: 'two', kind: 'schedule', date: '2026-09-30', endDate: '2026-10-12' }
  assert.equal(projectEntryOccursOn(calendarTodo, '2026-10-10'), true)
  assert.equal(projectEntryOccursOn(calendarTodo, '2026-10-11'), false)
  assert.equal(projectEntryOccursOn({ ...calendarTodo, date: null }, '2026-10-10'), false)
  assert.equal(projectEntryOccursOn({ ...calendarTodo, kind: 'memo' }, '2026-10-10'), false)
  assert.equal(projectEntryOccursOn(calendarSchedule, '2026-09-30'), true)
  assert.equal(projectEntryOccursOn(calendarSchedule, '2026-10-12'), true)
  assert.equal(projectEntryOccursOn(calendarSchedule, '2026-10-13'), false)
  const calendarResult = projectCalendar({ groups: [], projects: [{ id: 'one', name: 'First' }, { id: 'two', name: 'Second' }], entries: [calendarTodo, calendarSchedule, { ...calendarTodo, id: 'hidden', projectId: 'inaccessible' }] }, '2026-10-06')
  assert.equal(calendarResult.tasks.filter(item => item.date === '2026-10-10').length, 2)
  assert.equal(calendarResult.tasks.some(item => item.id.startsWith('hidden:')), false)
  assert.equal(calendarResult.tasks.find(item => item.id === 't:2026-10-10').completed, true)
  assert.equal(calendarResult.tasks.find(item => item.id === 's:2026-10-10').completed, false)
  assert.equal(projectCalendar({ groups: [], projects: [{ id: 'two', name: 'Second' }], entries: [{ ...calendarSchedule, date: '1900-01-01', endDate: '9999-12-31' }] }, '2026-10-06').tasks.length, 44)
  console.log('PASS: project calendar aggregates all projects; date ranges, undated/memo exclusions, access isolation and bounded expansion.')
  const filterData = { groups: [], projects: [{ id: 'one' }, { id: 'two' }], entries: [calendarTodo, calendarSchedule, { ...calendarTodo, id: 'memo', kind: 'memo' }, { ...calendarSchedule, id: 'private', projectId: 'missing' }] }
  const beforeFilter = JSON.stringify(filterData)
  assert.equal(visibleProjectEntries(filterData, { todo: true, schedule: false }).length, 1)
  assert.equal(visibleProjectEntries(filterData, { todo: false, schedule: true })[0].id, 's')
  assert.equal(visibleProjectEntries(filterData, { todo: false, schedule: false }).length, 0)
  assert.equal(JSON.stringify(filterData), beforeFilter)
  const days = Array.from({ length: 7 }, (_, i) => `2026-10-${String(5 + i).padStart(2, '0')}`)
  const barEntries = [calendarTodo, calendarSchedule, { ...calendarSchedule, id: 'overlap', date: '2026-10-06', endDate: '2026-10-07' }, { ...calendarSchedule, id: 'next', date: '2026-10-08', endDate: null }, { ...calendarSchedule, id: 'outside', date: '2026-10-13' }]
  const bars = projectWeekBars(barEntries, days)
  assert.equal(bars.length, 3)
  assert.equal(bars[0].start, 0); assert.equal(bars[0].end, 6)
  assert.equal(bars[0].startsHere, false); assert.equal(bars[0].endsHere, false)
  assert.equal(bars[1].lane, 1); assert.equal(bars[2].lane, 1)
  assert.equal(bars[2].start, bars[2].end)
  const manyBars = projectWeekBars(Array.from({ length: 5 }, (_, i) => ({ ...calendarSchedule, id: `overlap-${i}` })), days)
  assert.equal(manyBars[4].lane, 4)
  assert.equal(projectWeekBars([{ ...calendarSchedule, date: '1900-01-01', endDate: '9999-12-31' }], days).length, 1)
  console.log('PASS: project visibility filters preserve data; schedule bars clip at week edges; overlapping lanes and same-day schedules; bounded long ranges.')
  const { LocalTaskRepository } = await load('src/data/taskRepository.ts')
  const tasks = new LocalTaskRepository([])
  const task = await tasks.create({ title: 'Before', categoryId: 'one', date: '2026-10-01' })
  await tasks.toggle(task.id)
  await tasks.update(task.id, 'After')
  const updated = (await tasks.list())[0]
  assert.equal(updated.title, 'After')
  assert.equal(updated.completed, true)
  assert.equal(updated.date, '2026-10-01')
  assert.equal(updated.categoryId, 'one')
  await assert.rejects(() => tasks.update('missing', 'No orphan'))
  const { LocalCategoryRepository } = await load('src/data/categoryRepository.ts', { './seed': { categories: [{ id: 'one', name: 'One', color: '#555555' }, { id: 'two', name: 'Two', color: '#333333' }] } })
  const categories = new LocalCategoryRepository()
  await tasks.create({ title: 'Keep', categoryId: 'two', date: '2026-10-02' })
  await categories.remove('one')
  assert.equal((await categories.list()).length, 1)
  assert.equal((await tasks.list()).length, 1)
  assert.equal((await tasks.list())[0].title, 'Keep')
  const schedule = await load('src/data/habitSchedule.ts')
  const { habitRepository } = await load('src/data/habitRepository.ts', { './supabase': { supabase: null }, './habitSchedule': schedule, './itemColors': itemColors })
  const habit = await habitRepository.create('Daily', [0, 1, 2, 3, 4, 5, 6])
  const weekly = await habitRepository.create('Weekly', [1, 3, 5])
  await habitRepository.setCompleted(habit.id, '2026-10-01', true)
  await habitRepository.setCompleted(habit.id, '2026-10-02', true)
  await habitRepository.setCompleted(habit.id, '2026-10-01', false)
  const result = await habitRepository.list()
  assert.equal(result.habits.length, 2)
  assert.equal(weekly.weekdays.includes(4), false)
  assert.equal(result.completions.length, 1)
  assert.equal(result.completions[0].date, '2026-10-02')
  const changed = await habitRepository.update(habit.id, '  Edited daily  ', [5, 1, 5])
  assert.equal(changed.name, 'Edited daily')
  assert.deepEqual(Array.from(changed.weekdays), [1, 5])
  assert.equal(changed.id, habit.id)
  assert.equal(changed.createdAt, habit.createdAt)
  assert.equal((await habitRepository.list()).completions[0].date, '2026-10-02')
  await assert.rejects(() => habitRepository.update(habit.id, 'Bad weekdays', []))
  await assert.rejects(() => habitRepository.update(habit.id, 'Bad weekdays', [7]))
  await assert.rejects(() => habitRepository.update(habit.id, '   ', [1]))
  await assert.rejects(() => habitRepository.update('missing', 'No orphan', [1]))
  await habitRepository.setCompleted(weekly.id, '2026-10-02', true)
  await habitRepository.remove(habit.id)
  const afterDelete = await habitRepository.list()
  assert.equal(afterDelete.habits.length, 1)
  assert.equal(afterDelete.habits[0].id, weekly.id)
  assert.equal(afterDelete.completions.length, 1)
  assert.equal(afterDelete.completions[0].habitId, weekly.id)
  await assert.rejects(() => habitRepository.remove('missing'))
  assert.equal((await tasks.list())[0].title, 'Keep')
  const legacy = { id: 'history-test', name: 'History', weekdays: [0, 1, 2, 3, 4, 5, 6], createdAt: '2026-09-01T00:00:00Z' }
  const firstChange = { ...legacy, weekdays: [1], scheduleHistory: schedule.changedHabitHistory(legacy, [1], '2026-10-06') }
  assert.equal(schedule.habitIsScheduled(firstChange, '2026-10-05'), true)
  assert.equal(schedule.habitIsScheduled(firstChange, '2026-10-06'), false)
  assert.equal(schedule.habitIsScheduled(firstChange, '2026-10-12'), true)
  assert.equal(schedule.habitIsScheduled(firstChange, '2026-09-30'), true)
  const doneToday = [{ habitId: legacy.id, date: '2026-10-06' }]
  assert.equal(schedule.habitIsVisible(firstChange, '2026-10-06', doneToday), true)
  assert.equal(schedule.habitIsVisible(firstChange, '2026-10-07', doneToday), false)
  const sameDay = { ...firstChange, weekdays: [3], scheduleHistory: schedule.changedHabitHistory(firstChange, [3], '2026-10-06') }
  assert.equal(sameDay.scheduleHistory.length, 2)
  assert.equal(schedule.habitIsScheduled(sameDay, '2026-10-05'), true)
  assert.equal(schedule.habitIsScheduled(sameDay, '2026-10-07'), true)
  const nextChange = { ...sameDay, weekdays: [5], scheduleHistory: schedule.changedHabitHistory(sameDay, [5], '2026-10-08') }
  assert.equal(schedule.habitIsScheduled(nextChange, '2026-10-07'), true)
  assert.equal(schedule.habitIsScheduled(nextChange, '2026-10-09'), true)
  assert.equal(schedule.habitIsScheduled(nextChange, '2026-10-14'), false)
  assert.equal(schedule.changedHabitHistory(nextChange, [5], '2026-10-09').length, 3)
  assert.equal(schedule.habitIsScheduled(nextChange, '2026-08-31'), false)
  memory.set('haru.habits.v1', JSON.stringify([legacy]))
  memory.set('haru.habitCompletions.v1', JSON.stringify(doneToday))
  const storedChange = await habitRepository.update(legacy.id, 'History edited', [1])
  assert.equal(storedChange.scheduleHistory.length, 2)
  assert.equal((await habitRepository.list()).habits[0].scheduleHistory.length, 2)
  assert.equal((await habitRepository.list()).completions.length, 1)
  let rpcCalled = false
  const safeCloud = await load('src/data/habitRepository.ts', {
    './supabase': { supabase: {
      from: () => ({ select: () => ({ eq: () => ({ single: async () => ({ error: { message: 'Missing schedule_history' } }) }) }) }),
      rpc: async () => { rpcCalled = true },
    } }, './habitSchedule': schedule, './itemColors': itemColors,
  })
  await assert.rejects(() => safeCloud.habitRepository.update(legacy.id, 'Safe', [1]))
  assert.equal(rpcCalled, false)
  const holidayHabit = { ...legacy, excludeHolidays: true, scheduleHistory: schedule.changedHabitHistory(legacy, legacy.weekdays, '2026-10-06', true) }
  assert.equal(schedule.habitIsScheduled(holidayHabit, '2026-10-05', true), true)
  assert.equal(schedule.habitIsScheduled(holidayHabit, '2026-10-09', true), false)
  assert.equal(schedule.habitIsScheduled(holidayHabit, '2026-10-09', false), true)
  assert.equal(schedule.habitIsScheduled(holidayHabit, '2026-10-09', null), false)
  assert.equal(schedule.habitIsScheduled(legacy, '2026-10-09', null), true)
  assert.equal(schedule.habitIsVisible(holidayHabit, '2026-10-09', [{ habitId: legacy.id, date: '2026-10-09' }], true), true)
  const includeAgain = { ...holidayHabit, excludeHolidays: false, scheduleHistory: schedule.changedHabitHistory(holidayHabit, holidayHabit.weekdays, '2026-10-10', false) }
  assert.equal(schedule.habitIsScheduled(includeAgain, '2026-10-09', true), false)
  assert.equal(schedule.habitIsScheduled(includeAgain, '2026-12-25', true), true)
  let holidayFetches = 0
  const holidayData = await load('src/data/koreanHolidays.ts', {}, {
    AbortSignal, fetch: async () => { holidayFetches++; return { ok: true, json: async () => ({ '2026-10-09': ['한글날'], '2026-10-05': ['대체공휴일(개천절)'] }) } },
  })
  assert.equal((await holidayData.loadKoreanHolidays(2026)).holidays['2026-10-09'][0], '한글날')
  await holidayData.loadKoreanHolidays(2026)
  assert.equal(holidayFetches, 1)
  assert.throws(() => holidayData.validateHolidayData({ '2026-10-09': [] }, 2026))
  assert.throws(() => holidayData.validateHolidayData({ '2027-10-09': ['한글날'] }, 2026))
  const failedHolidays = await load('src/data/koreanHolidays.ts', {}, { AbortSignal, fetch: async () => { throw new Error('offline') } })
  await assert.rejects(() => failedHolidays.loadKoreanHolidays(2028))
  const cached = JSON.parse(memory.get('haru.krHolidays.v1.2026'))
  memory.set('haru.krHolidays.v1.2026', JSON.stringify({ ...cached, fetchedAt: 0 }))
  assert.equal((await failedHolidays.loadKoreanHolidays(2026)).stale, true)
  const { projectRepository } = await load('src/data/projectRepository.ts', { './supabase': { supabase: null }, './itemColors': itemColors })
  const company = await projectRepository.createGroup('회사', '  회사 업무와 일정\n프로젝트 기록  ')
  assert.equal(company.description, '회사 업무와 일정\n프로젝트 기록')
  assert.equal((await projectRepository.updateGroup(company.id, '회사')).description, company.description)
  assert.equal((await projectRepository.updateGroup(company.id, '회사', '수정한 설명')).description, '수정한 설명')
  assert.equal((await projectRepository.list()).groups[0].description, '수정한 설명')
  await assert.rejects(() => projectRepository.updateGroup(company.id, '회사', '가'.repeat(1001)))
  assert.equal((await projectRepository.list()).groups[0].description, '수정한 설명')
  assert.equal((await projectRepository.updateGroup(company.id, '회사', '')).description, '')
  await assert.rejects(() => projectRepository.createGroup('너무 긴 설명', '가'.repeat(1001)))
  const team = await projectRepository.createGroup('팀플')
  const website = await projectRepository.createProject(company.id, '웹사이트')
  const secondProject = await projectRepository.createProject(company.id, '앱')
  const keepProject = await projectRepository.createProject(team.id, '발표')
  const draft = { kind: 'todo', title: '시안 확인', content: '설명', date: '2026-10-10', endDate: null }
  const projectTodo = await projectRepository.saveEntry(website.id, draft)
  await projectRepository.toggleEntry(projectTodo.id, true)
  const editedEntry = await projectRepository.saveEntry(website.id, { ...draft, title: '수정 시안 확인' }, projectTodo.id)
  assert.equal(editedEntry.completed, true)
  assert.equal(editedEntry.createdAt, projectTodo.createdAt)
  await projectRepository.saveEntry(website.id, { kind: 'schedule', title: '스프린트', content: '', date: '2026-10-10', endDate: '2026-10-15' })
  await projectRepository.saveEntry(secondProject.id, { kind: 'memo', title: '회의', content: '여러 줄\n메모', date: null, endDate: null })
  await projectRepository.saveEntry(keepProject.id, { kind: 'memo', title: '유지', content: '별도 그룹', date: null, endDate: null })
  await assert.rejects(() => projectRepository.createProject('missing', 'No orphan'))
  await assert.rejects(() => projectRepository.saveEntry(website.id, { ...draft, date: '2026-02-30' }))
  await assert.rejects(() => projectRepository.saveEntry(website.id, { ...draft, kind: 'schedule', date: null }))
  await assert.rejects(() => projectRepository.saveEntry(website.id, { ...draft, kind: 'schedule', endDate: '2026-10-01' }))
  await assert.rejects(() => projectRepository.createGroup(' '))
  await assert.rejects(() => projectRepository.saveEntry(keepProject.id, draft, projectTodo.id))
  assert.equal((await projectRepository.updateGroup(company.id, '회사 업무')).name, '회사 업무')
  assert.equal((await projectRepository.updateProject(website.id, '리뉴얼')).name, '리뉴얼')
  await projectRepository.removeProject(website.id)
  assert.equal((await projectRepository.list()).entries.length, 2)
  await projectRepository.removeGroup(company.id)
  const projectResult = await projectRepository.list()
  assert.equal(projectResult.groups.length, 1)
  assert.equal(projectResult.projects.length, 1)
  assert.equal(projectResult.entries[0].title, '유지')
  await projectRepository.removeEntry(projectResult.entries[0].id)
  assert.equal((await projectRepository.list()).entries.length, 0)
  assert.equal((await tasks.list())[0].title, 'Keep')
  assert.equal((await habitRepository.list()).habits[0].name, 'History edited')
  const colorHabit = (await habitRepository.list()).habits[0]
  const completionsBeforeColor = JSON.stringify((await habitRepository.list()).completions)
  const coloredHabit = await habitRepository.update(colorHabit.id, colorHabit.name, colorHabit.weekdays, !!colorHabit.excludeHolidays, '#5276b8')
  assert.equal(coloredHabit.color, '#5276b8')
  assert.equal(JSON.stringify(coloredHabit.scheduleHistory), JSON.stringify(colorHabit.scheduleHistory))
  assert.equal(JSON.stringify((await habitRepository.list()).completions), completionsBeforeColor)
  assert.equal((await habitRepository.update(coloredHabit.id, coloredHabit.name, coloredHabit.weekdays, !!coloredHabit.excludeHolidays)).color, '#5276b8')
  const coloredProject = await projectRepository.updateProject(keepProject.id, '발표', '#8a63a8')
  assert.equal(coloredProject.color, '#8a63a8')
  assert.equal((await projectRepository.updateProject(keepProject.id, '발표 수정')).color, '#8a63a8')
  assert.equal(projectCalendar(await projectRepository.list(), '2026-10-06').categories[0].color, '#8a63a8')
  await assert.rejects(() => projectRepository.updateProject(keepProject.id, 'Invalid', 'red'))
  await assert.rejects(() => habitRepository.update(colorHabit.id, 'Invalid', [1], false, 'bad'))
  console.log('PASS: habit/project colors persist; legacy edit preserves colors; calendar uses chosen colors; history/completions preserved; invalid colors rejected.')
  console.log('PASS: project group/project/entry CRUD; schedule validation; cascading deletion isolation; task/habit data preserved.')
  console.log('PASS: task/category isolation; habit history/edit/delete; holiday exclusions and completed records; unknown holiday safety; holiday cache/validation/offline fallback; missing cloud migration safety.')
}
main().catch(error => { console.error(error); process.exitCode = 1 })
